### ISSUE TITLE
clean up autoport

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/babel#14]
It's time to clean up babel/autoport/, deleting directories for sims that have been published.

From 2/25/2016 developer meeting notes:

> JB: There are _en.json strings in the autoport dir in babel.  I accidentally ended up in one of these files when working on the strings for RIAW, though I quickly realized my mistake.  These files may be useful for non-ported sims, but useless and potentially a bit confusing for ported sims.  Shall we remove them?  For that matter, should we remove all autoported strings for translated sims once we’ve decided whether or not to move them over?
• SR: I’d recommend to remove them for sims that have already been created, keep them for sims that have not yet been created.   When a new sim is created, we should move the autoport strings over.
• JB: We need to be careful doing this because updates to babel outside of Rosetta may mess up Rosetta.  The strings would need to be removed, pushed, then a manual pull on figaro.
• JB: I’ll clean this up for currently published sims, i.e. delete the autoported strings, then do it again some time in the future.

**Comment by pixelzoom** [comment]
To be deleted:

charges-and-fields
gravity-and-orbits
molecule-polarity
plinko-probability
projectile-motion (about to be published)
states-of-matter (?)

**Comment by jbphet** [comment]
I deleted the identified directories, including states-of-matter, which was labeled with a question mark in the list. 

On the developer channel in Slack, there was some discussion yesterday where several people said that we had decided not to use these strings any more and just start fresh on each sim.  If that's the case, we should just blow the whole `autoport` directory away.  Labeling for developer meeting to decide.

My vote, at least for now, would be to leave this around and have the developer decide.  My motivation is that I'm currently working on Gene Expression, and the strings from that one will carry over pretty well since it is largely unchanged from the Java versions.  One of my next sims will be Energy Forms and Changes, and this may well be true for that sim too.  We should add a checklist item to have the developer decide whether to import the strings and do so (or not), and then delete the auto-port file.

**Comment by pixelzoom** [comment]
>  My motivation is that I'm currently working on Gene Expression, and the strings from that one will carry over pretty well since it is largely unchanged from the Java versions. 

I'm fine with keeping `babel/autoport/` for situations where the strings _and keys_ are mostly unchanged from Java/Flash, and leaving it up to developer discretion to decide whether to port them.

+1 for adding a checklist item, presumably to the [master checklist](https://github.com/phetsims/phet-info/blob/master/checklists/sim_new_checklist.md) since this is for new sims.

**Comment by pixelzoom** [comment]
8/17/17 dev meeting consensus:   Yes, as proposed in https://github.com/phetsims/babel/issues/14#issuecomment-321937537.

I'll add to master checklist.

**Comment by pixelzoom** [comment]
Master checklist has been updated. Closing.
