### ISSUE TITLE
Can developers commit to babel?

### ISSUE THREAD

**Issue by samreid** [phetsims/babel#7]
As part of https://github.com/phetsims/chipper/issues/131 I have ported the strings from Java, Flash and Flex to babel in a new directory "autoport".  It appears my commit caused failures in rosetta, and many error emails were sent out.  @jonathanolson and I looked into it and it seems like rosetta is using the github api for doing git commits, and we aren't sure how it got out of sync, or if all of the commits must be done through the same tooling.

**Comment by jbphet** [comment]
I just looked at Rosetta's logs and the babel commit history, and it looks like translations were being submitted at roughly the same time as @samreid was making these commits to the "autoport" directory.  This might mean that a push from Rosetta failed because commits had been pushed to babel since Rosetta had last pulled it during the translation process.  This happens to us fairly frequently during code development, and we generally just rebase and then submit.  Rosetta is probably not adaptive enough to do this, at least not yet.

This is related to  https://github.com/phetsims/rosetta/issues/105, and involves the handling of error legs in the interaction between Rosetta and GitHub/babel.

To answer the original question "Can developers commit to babel", the answer is yes, but it might cause weird things like this to occur, so it would be best to avoid direct commits as much as possible.  At some point, Rosetta may be much better at handling such things, but it's likely to be a while given our other priorities.

As it turns out, the person doing the translations that collided with @samreid's commits is @arouinfar's husband, so we can get more information about what exactly occurred from the two of them.

@samreid - you said, "many error emails were sent out".  I only received two.  Can you give me more information about what you received?  I want to make sure I'm not missing anything.

**Comment by samreid** [comment]
> @samreid - you said, "many error emails were sent out". I only received two. Can you give me more information about what you received? I want to make sure I'm not missing anything.

I am not receiving these emails, but I thought @jonathanolson saw many of them.  @jonathanolson can you chime in?

> it would be best to avoid direct commits as much as possible

Our process is to port strings from Java and Flash.  Should we avoid these direct commits?

**Comment by jonathanolson** [comment]
I saw just 2 error emails. Just was complaining about how outlook displayed the github notifications for the threat that the babel commits were linked to!

**Comment by samreid** [comment]
Ah, makes sense, thanks!

**Comment by jbphet** [comment]
> Our process is to port strings from Java and Flash. Should we avoid these direct commits?

For this, I think we'll just have to live with the risk of collisions.  Re-submitting a translation seems to work fine if something goes wrong, and things have only gone wrong once so far in something like 100 translations.  As mentioned previously, at some point we can put some effort into making the whole system more robust.  So, when I say that we should "avoid direct commits as much as possible", I mean that we shouldn't do a lot of manual tweaking of the string files.

@samreid - anything else to do here?

**Comment by jbphet** [comment]
@samreid said that he is fine with closing this.
